import type { Socket } from "socket.io-client";

export type WebRTCSignalPayload = {
  sessionId: string;
  offer?: RTCSessionDescriptionInit;
  answer?: RTCSessionDescriptionInit;
  candidate?: RTCIceCandidateInit;
};

type WebRTCServiceOptions = {
  socket: Socket;
  sessionId: string;
  localStream: MediaStream;

  /**
   * ICE servers generated by the backend.
   *
   * These are provided by Twilio Network Traversal
   * and contain STUN/TURN configuration.
   */
  iceServers: RTCIceServer[];

  onRemoteStream: (stream: MediaStream) => void;
  onConnectionStateChange?: (
    state: RTCPeerConnectionState
  ) => void;
};

const RECONNECT_DELAY = 2000;

export class WebRTCService {
  private readonly socket: Socket;
  private readonly sessionId: string;
  private readonly localStream: MediaStream;

  /**
   * Dynamic STUN/TURN servers received from backend.
   */
  private readonly iceServers: RTCIceServer[];

  private readonly onRemoteStream: (
    stream: MediaStream
  ) => void;

  private readonly onConnectionStateChange?: (
    state: RTCPeerConnectionState
  ) => void;

  private peerConnection: RTCPeerConnection | null = null;

  private pendingIceCandidates: RTCIceCandidateInit[] = [];

  private remoteDescriptionSet = false;

  private destroyed = false;

  /**
   * Prevent multiple reconnection attempts
   * from running at the same time.
   */
  private reconnecting = false;

  /**
   * Used to prevent multiple offers from being
   * created during the same recovery attempt.
   */
  private offerInProgress = false;

  /**
   * Store the last known remote stream.
   *
   * When the peer connection is recreated,
   * the new remote tracks can replace this.
   */
  private remoteStream: MediaStream | null = null;

  constructor({
    socket,
    sessionId,
    localStream,
    iceServers,
    onRemoteStream,
    onConnectionStateChange,
  }: WebRTCServiceOptions) {
    this.socket = socket;
    this.sessionId = sessionId;
    this.localStream = localStream;
    this.iceServers = iceServers;
    this.onRemoteStream = onRemoteStream;
    this.onConnectionStateChange =
      onConnectionStateChange;

    console.log(
      `[WebRTC] Initialized with ${iceServers.length} ICE servers.`
    );

    this.setupSocketListeners();
  }

  // ======================================================
  // CREATE PEER CONNECTION
  // ======================================================

  private createPeerConnection(): RTCPeerConnection {
    if (this.peerConnection) {
      return this.peerConnection;
    }

    console.log(
      "[WebRTC] Creating RTCPeerConnection..."
    );

    const peerConnection =
  new RTCPeerConnection({
    iceServers: this.iceServers,
  });

    this.peerConnection = peerConnection;

    console.log(
      "[WebRTC] RTCPeerConnection created with Twilio ICE servers."
    );

    // ----------------------------------------------------
    // LOCAL TRACKS
    // ----------------------------------------------------

    this.localStream
      .getTracks()
      .forEach((track) => {
        console.log(
          "[WebRTC] Adding local track:",
          track.kind
        );

        peerConnection.addTrack(
          track,
          this.localStream
        );
      });

    // ----------------------------------------------------
    // REMOTE TRACK
    // ----------------------------------------------------

    peerConnection.ontrack = (event) => {
      console.log(
        "[WebRTC] Remote track received:",
        event.track.kind
      );

      /**
       * WebRTC may fire ontrack once for audio
       * and once for video.
       *
       * Prefer the stream provided by the browser.
       */
      const [incomingStream] =
        event.streams;

      if (incomingStream) {
        this.remoteStream =
          incomingStream;

        this.onRemoteStream(
          incomingStream
        );

        return;
      }

      /**
       * Fallback for browsers that don't
       * provide event.streams.
       */
      if (!this.remoteStream) {
        this.remoteStream =
          new MediaStream();
      }

      this.remoteStream.addTrack(
        event.track
      );

      this.onRemoteStream(
        this.remoteStream
      );
    };

    // ----------------------------------------------------
    // ICE CANDIDATE
    // ----------------------------------------------------

    peerConnection.onicecandidate = (
      event
    ) => {
      if (!event.candidate) {
        return;
      }

      const candidate =
        event.candidate.toJSON();

      console.log(
        "[WebRTC] Sending ICE candidate:",
        candidate.candidate
      );

      this.socket.emit(
        "webrtc-ice-candidate",
        {
          sessionId: this.sessionId,
          candidate,
        }
      );
    };

    // ----------------------------------------------------
    // CONNECTION STATE
    // ----------------------------------------------------

    peerConnection.onconnectionstatechange =
      () => {
        const state =
          peerConnection.connectionState;

        console.log(
          "[WebRTC] Connection state:",
          state
        );

        this.onConnectionStateChange?.(
          state
        );

        if (this.destroyed) {
          return;
        }

        if (state === "failed") {
          console.warn(
            "[WebRTC] Connection failed. Attempting recovery..."
          );

          void this.handleConnectionFailure();
        }

        if (state === "disconnected") {
          console.warn(
            "[WebRTC] Connection disconnected."
          );

          void this.handleConnectionFailure();
        }

        if (state === "connected") {
  console.log(
    "[WebRTC] Connection successfully established."
  );

  this.reconnecting = false;

  void this.logSelectedCandidatePair();
}
      };

    // ----------------------------------------------------
    // ICE CONNECTION STATE
    // ----------------------------------------------------

    peerConnection.oniceconnectionstatechange =
      () => {
        const state =
          peerConnection.iceConnectionState;

        console.log(
          "[WebRTC] ICE connection state:",
          state
        );

        if (this.destroyed) {
          return;
        }

        if (state === "failed") {
          console.warn(
            "[WebRTC] ICE connection failed. Attempting recovery..."
          );

          void this.handleConnectionFailure();
        }

        if (state === "disconnected") {
          console.warn(
            "[WebRTC] ICE connection disconnected."
          );

          void this.handleConnectionFailure();
        }

        if (state === "connected") {
          console.log(
            "[WebRTC] ICE connection successfully established."
          );
        }
      };

    return peerConnection;
  }

 private async logSelectedCandidatePair(): Promise<void> {
  if (!this.peerConnection) {
    return;
  }

  try {
    const stats = await this.peerConnection.getStats();

    let selectedPairId: string | undefined;

    // Find the selected candidate pair from transport stats
    stats.forEach((report) => {
      if (report.type === "transport") {
        const transport = report as RTCTransportStats;

        if (transport.selectedCandidatePairId) {
          selectedPairId = transport.selectedCandidatePairId;
        }
      }
    });

    if (!selectedPairId) {
      console.log(
        "[WebRTC] No selected ICE candidate pair found."
      );
      return;
    }

    const selectedPair =
      stats.get(selectedPairId);

    if (
      !selectedPair ||
      selectedPair.type !== "candidate-pair"
    ) {
      console.log(
        "[WebRTC] Selected candidate pair stats not found."
      );
      return;
    }

    const candidatePair =
      selectedPair as RTCIceCandidatePairStats;

    const localCandidate =
      stats.get(candidatePair.localCandidateId);

    const remoteCandidate =
      stats.get(candidatePair.remoteCandidateId);

    console.log(
      "[WebRTC] SELECTED ICE CANDIDATE PAIR:",
      {
        localCandidateType:
          localCandidate?.type === "local-candidate"
            ? localCandidate.candidateType
            : undefined,

        remoteCandidateType:
          remoteCandidate?.type === "remote-candidate"
            ? remoteCandidate.candidateType
            : undefined,

        localCandidate,
        remoteCandidate,
      }
    );
  } catch (error) {
    console.error(
      "[WebRTC] Failed to inspect selected ICE candidate pair:",
      error
    );
  }
}
  // ======================================================
  // SOCKET LISTENERS
  // ======================================================

  private setupSocketListeners(): void {
    this.socket.on(
      "webrtc-offer",
      this.handleOffer
    );

    this.socket.on(
      "webrtc-answer",
      this.handleAnswer
    );

    this.socket.on(
      "webrtc-ice-candidate",
      this.handleIceCandidate
    );
  }

  // ======================================================
  // CREATE OFFER
  // ======================================================

  public async createOffer(): Promise<void> {
    if (this.destroyed) {
      return;
    }

    if (this.offerInProgress) {
      console.log(
        "[WebRTC] Offer creation already in progress."
      );

      return;
    }

    const peerConnection =
      this.createPeerConnection();

    try {
      this.offerInProgress = true;

      console.log(
        "[WebRTC] Creating offer..."
      );

      const offer =
        await peerConnection.createOffer({
          offerToReceiveAudio: true,
          offerToReceiveVideo: true,
        });

      if (this.destroyed) {
        return;
      }

      await peerConnection.setLocalDescription(
        offer
      );

      if (this.destroyed) {
        return;
      }

      this.socket.emit(
        "webrtc-offer",
        {
          sessionId: this.sessionId,
          offer,
        }
      );

      console.log(
        "[WebRTC] Offer sent."
      );
    } catch (error) {
      console.error(
        "[WebRTC] Failed to create offer:",
        error
      );

      throw error;
    } finally {
      this.offerInProgress = false;
    }
  }

  // ======================================================
  // HANDLE OFFER
  // ======================================================

  private handleOffer = async (
    data: {
      userId: string;
      offer: RTCSessionDescriptionInit;
    }
  ): Promise<void> => {
    if (this.destroyed) {
      return;
    }

    try {
      console.log(
        "[WebRTC] Offer received from:",
        data.userId
      );

      const peerConnection =
        this.createPeerConnection();

      /**
       * Reset this because a new offer represents
       * a new negotiation.
       */
      this.remoteDescriptionSet =
        false;

      await peerConnection.setRemoteDescription(
        new RTCSessionDescription(
          data.offer
        )
      );

      this.remoteDescriptionSet = true;

      console.log(
        "[WebRTC] Remote offer applied."
      );

      await this.flushPendingIceCandidates();

      const answer =
        await peerConnection.createAnswer();

      if (this.destroyed) {
        return;
      }

      await peerConnection.setLocalDescription(
        answer
      );

      if (this.destroyed) {
        return;
      }

      this.socket.emit(
        "webrtc-answer",
        {
          sessionId: this.sessionId,
          answer,
        }
      );

      console.log(
        "[WebRTC] Answer sent."
      );
    } catch (error) {
      console.error(
        "[WebRTC] Failed to handle offer:",
        error
      );
    }
  };

  // ======================================================
  // HANDLE ANSWER
  // ======================================================

  private handleAnswer = async (
    data: {
      userId: string;
      answer: RTCSessionDescriptionInit;
    }
  ): Promise<void> => {
    if (this.destroyed) {
      return;
    }

    try {
      console.log(
        "[WebRTC] Answer received from:",
        data.userId
      );

      if (!this.peerConnection) {
        console.warn(
          "[WebRTC] Received answer without peer connection."
        );

        return;
      }

      await this.peerConnection.setRemoteDescription(
        new RTCSessionDescription(
          data.answer
        )
      );

      this.remoteDescriptionSet = true;

      console.log(
        "[WebRTC] Remote answer applied."
      );

      await this.flushPendingIceCandidates();

      console.log(
        "[WebRTC] Remote answer negotiation completed."
      );
    } catch (error) {
      console.error(
        "[WebRTC] Failed to handle answer:",
        error
      );
    }
  };

  // ======================================================
  // HANDLE ICE CANDIDATE
  // ======================================================

  private handleIceCandidate = async (
    data: {
      userId: string;
      candidate: RTCIceCandidateInit;
    }
  ): Promise<void> => {
    if (this.destroyed) {
      return;
    }

    try {
      console.log(
        "[WebRTC] ICE candidate received from:",
        data.userId
      );

      if (!this.peerConnection) {
        console.warn(
          "[WebRTC] Peer connection not ready. Queueing ICE candidate."
        );

        this.pendingIceCandidates.push(
          data.candidate
        );

        return;
      }

      if (!this.remoteDescriptionSet) {
        console.log(
          "[WebRTC] Remote description not ready. Queueing ICE candidate."
        );

        this.pendingIceCandidates.push(
          data.candidate
        );

        return;
      }

      await this.peerConnection.addIceCandidate(
        new RTCIceCandidate(
          data.candidate
        )
      );

      console.log(
        "[WebRTC] ICE candidate added."
      );
    } catch (error) {
      console.error(
        "[WebRTC] Failed to handle ICE candidate:",
        error
      );
    }
  };

  // ======================================================
  // FLUSH PENDING ICE CANDIDATES
  // ======================================================

  private async flushPendingIceCandidates(): Promise<void> {
    if (!this.peerConnection) {
      return;
    }

    if (!this.remoteDescriptionSet) {
      return;
    }

    if (!this.pendingIceCandidates.length) {
      return;
    }

    console.log(
      `[WebRTC] Adding ${this.pendingIceCandidates.length} pending ICE candidates.`
    );

    const candidates = [
      ...this.pendingIceCandidates,
    ];

    this.pendingIceCandidates = [];

    for (const candidate of candidates) {
      try {
        if (this.destroyed) {
          return;
        }

        await this.peerConnection.addIceCandidate(
          new RTCIceCandidate(
            candidate
          )
        );
      } catch (error) {
        console.error(
          "[WebRTC] Failed to add pending ICE candidate:",
          error
        );
      }
    }
  }

  // ======================================================
  // CONNECTION FAILURE HANDLER
  // ======================================================

  private async handleConnectionFailure(): Promise<void> {
    if (this.destroyed) {
      return;
    }

    /**
     * Prevent multiple recovery attempts
     * when both connectionState and
     * iceConnectionState report failure.
     */
    if (this.reconnecting) {
      console.log(
        "[WebRTC] Recovery already in progress."
      );

      return;
    }

    this.reconnecting = true;

    console.log(
      "[WebRTC] Starting connection recovery..."
    );

    try {
      /**
       * Give the connection a small amount
       * of time to recover naturally.
       */
      await this.delay(
        RECONNECT_DELAY
      );

      if (this.destroyed) {
        return;
      }

      /**
       * Check whether the connection recovered
       * during the waiting period.
       */
      const currentState =
        this.peerConnection?.connectionState;

      if (
        currentState === "connected"
      ) {
        console.log(
          "[WebRTC] Connection recovered automatically."
        );

        this.reconnecting = false;

        return;
      }

      /**
       * ICE restart is preferable to immediately
       * destroying the entire peer connection.
       */
      if (this.peerConnection) {
        console.log(
          "[WebRTC] Attempting ICE restart..."
        );

        const offer =
          await this.peerConnection.createOffer({
            iceRestart: true,
            offerToReceiveAudio: true,
            offerToReceiveVideo: true,
          });

        if (this.destroyed) {
          return;
        }

        await this.peerConnection.setLocalDescription(
          offer
        );

        if (this.destroyed) {
          return;
        }

        this.socket.emit(
          "webrtc-offer",
          {
            sessionId:
              this.sessionId,
            offer,
          }
        );

        console.log(
          "[WebRTC] ICE restart offer sent."
        );
      }
    } catch (error) {
      console.error(
        "[WebRTC] Connection recovery failed:",
        error
      );
    } finally {
      this.reconnecting = false;
    }
  }

  // ======================================================
  // DELAY
  // ======================================================

  private delay(
    milliseconds: number
  ): Promise<void> {
    return new Promise(
      (resolve) => {
        window.setTimeout(
          resolve,
          milliseconds
        );
      }
    );
  }

  // ======================================================
  // DESTROY
  // ======================================================

  public destroy(): void {
    if (this.destroyed) {
      return;
    }

    console.log(
      "[WebRTC] Destroying peer connection."
    );

    this.destroyed = true;

    this.reconnecting = false;

    this.offerInProgress = false;

    // ----------------------------------------------------
    // REMOVE SOCKET LISTENERS
    // ----------------------------------------------------

    this.socket.off(
      "webrtc-offer",
      this.handleOffer
    );

    this.socket.off(
      "webrtc-answer",
      this.handleAnswer
    );

    this.socket.off(
      "webrtc-ice-candidate",
      this.handleIceCandidate
    );

    // ----------------------------------------------------
    // CLOSE PEER CONNECTION
    // ----------------------------------------------------

    if (this.peerConnection) {
      this.peerConnection.ontrack =
        null;

      this.peerConnection.onicecandidate =
        null;

      this.peerConnection.onconnectionstatechange =
        null;

      this.peerConnection.oniceconnectionstatechange =
        null;

      this.peerConnection.close();

      this.peerConnection = null;
    }

    // ----------------------------------------------------
    // CLEAR STATE
    // ----------------------------------------------------

    this.pendingIceCandidates = [];

    this.remoteDescriptionSet =
      false;

    this.remoteStream = null;
  }
}